app:
  env: "development"
  name: "go-chat"
  port:
    rest: ":1313"

db:
  postgre:
    host: "localhost"
    port: "5432"
    user: "postgres"
    pass: "example"
    name: "gochat"
    ssl: "disable"